apiVersion: v1
kind: Service
metadata:
  name: {{ include "deepseek-harness.fullname" . }}
  labels:
    {{- include "deepseek-harness.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
    - name: desktop
      port: {{ .Values.service.desktopPort }}
      protocol: TCP
      targetPort: desktop
  selector:
    {{- include "deepseek-harness.selectorLabels" . | nindent 4 }}
